Weight decay on main fork
vladfi1/slippi-ai pull request #23
Opened 2021-06-09 18:32 UTC by wmcnicho

@vladfi1 

This is a new PR with the same change from  https://github.com/wmcnicho/slippi-ai/pull/1

2021-06-09 18:33 UTC, wmcnicho commented
Something's fishy. The other 12 commits should be addressed by https://github.com/vladfi1/slippi-ai/pull/22.

I'll do some git digging

2021-06-09 18:43 UTC, wmcnicho commented
Preliminary results show this having very negative results on loss. Going to enqueue another with much more gradual decay:

![image](https://user-images.githubusercontent.com/3289054/121410930-17836680-c931-11eb-8af2-0480514ac931.png)

2021-09-12 16:56 UTC, vladfi1 requested changes

2021-09-12 16:56 UTC, vladfi1 commented on learner.py
> +      decay_rate=float(1)
`decay_rate=1.0`

2021-09-12 16:56 UTC, vladfi1 commented on learner.py
> +      decay_rate=float,
`decay_rate: float`

2021-09-12 16:56 UTC, vladfi1 commented on learner.py
> +    # TODO pass this as a flag
See TODO

2022-02-07 16:48 UTC, vladfi1 commented
Closing, as weight decay has already been merged in.

2022-02-07 16:48 UTC, closed without merging